// <auto-generated />
using System;
using FormBuilder.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(FormBuilderDbContext))]
    [Migration("20260506130000_AddBusinessRules")]
    partial class AddBusinessRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ── BusinessRule ──────────────────────────────────────────────────

            modelBuilder.Entity("FormBuilder.Backend.BusinessRule", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("BrokerDescription").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClientDescription").HasColumnType("nvarchar(max)");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<string>("FormSchemaId").HasColumnType("nvarchar(450)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("RuleReference").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");

                    b.HasKey("Id");
                    b.HasIndex("FormSchemaId");
                    b.HasIndex("RuleReference").IsUnique();
                    b.ToTable("BusinessRules");
                });

            modelBuilder.Entity("FormBuilder.Backend.RuleCondition", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessRuleId").HasColumnType("int");
                    b.Property<string>("FailMessage").HasColumnType("nvarchar(max)");
                    b.Property<string>("LeftExpression").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Operator").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<int>("Order").HasColumnType("int");
                    b.Property<string>("RightExpression").IsRequired().HasColumnType("nvarchar(max)");

                    b.HasKey("Id");
                    b.HasIndex("BusinessRuleId");
                    b.ToTable("RuleConditions");
                });

            // ── All other entities (unchanged from previous migration) ─────────

            modelBuilder.Entity("FormBuilder.Backend.Address", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("BuildingName").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("BuildingNumber").HasMaxLength(12).HasColumnType("nvarchar(12)");
                    b.Property<int>("CompanyId").HasColumnType("int");
                    b.Property<string>("Country").HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("DepartmentName").HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.Property<string>("DependentLocality").HasMaxLength(35).HasColumnType("nvarchar(35)");
                    b.Property<string>("DependentThoroughfareDescriptor").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("DependentThoroughfareName").HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.Property<string>("DoubleDependentLocality").HasMaxLength(35).HasColumnType("nvarchar(35)");
                    b.Property<string>("OrganisationName").HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.Property<string>("POBox").HasMaxLength(6).HasColumnType("nvarchar(6)");
                    b.Property<string>("PostTown").HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<string>("Postcode").HasMaxLength(8).HasColumnType("nvarchar(8)");
                    b.Property<string>("SubBuildingName").HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<string>("ThoroughfareDescriptor").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("ThoroughfareName").HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.Property<int>("Type").HasColumnType("int");
                    b.HasKey("Id"); b.HasIndex("CompanyId"); b.ToTable("Addresses");
                });

            modelBuilder.Entity("FormBuilder.Backend.ApiRequestLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<long>("DurationMs").HasColumnType("bigint");
                    b.Property<string>("Endpoint").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ErrorMessage").HasColumnType("nvarchar(max)");
                    b.Property<string>("Integration").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Method").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("RequestBody").HasColumnType("nvarchar(max)");
                    b.Property<string>("RequestHeaders").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("RequestedAt").HasColumnType("datetime2");
                    b.Property<string>("ResponseBody").HasColumnType("nvarchar(max)");
                    b.Property<int?>("StatusCode").HasColumnType("int");
                    b.HasKey("Id"); b.ToTable("ApiRequestLogs");
                });

            modelBuilder.Entity("FormBuilder.Backend.Application", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("BrokerId").HasColumnType("int");
                    b.Property<int?>("ClientId").HasColumnType("int");
                    b.Property<int?>("CompanyId").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int?>("CurrentStageId").HasColumnType("int");
                    b.Property<string>("FormData").HasColumnType("nvarchar(max)");
                    b.Property<string>("FormSchemaId").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<int>("FormSchemaVersion").HasColumnType("int");
                    b.Property<int?>("NetworkId").HasColumnType("int");
                    b.Property<string>("PublicReference").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<DateTime?>("SubmittedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<int>("Version").HasColumnType("int");
                    b.Property<int?>("WorkflowId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("BrokerId"); b.HasIndex("ClientId"); b.HasIndex("CompanyId");
                    b.HasIndex("CurrentStageId"); b.HasIndex("FormSchemaId"); b.HasIndex("NetworkId");
                    b.HasIndex("PublicReference").IsUnique(); b.HasIndex("WorkflowId");
                    b.ToTable("Applications");
                });

            modelBuilder.Entity("FormBuilder.Backend.BankDetails", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("AccountName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("AccountNumber").IsRequired().HasMaxLength(8).HasColumnType("nvarchar(8)");
                    b.Property<string>("BankName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<int>("CompanyId").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("SortCode").IsRequired().HasMaxLength(6).HasColumnType("nvarchar(6)");
                    b.HasKey("Id"); b.HasIndex("CompanyId"); b.ToTable("BankDetails");
                });

            modelBuilder.Entity("FormBuilder.Backend.BrandingSettings", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("AccentColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("BackgroundColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("CardColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("FontBody").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("FontHeading").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("MutedTextColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("PrimaryColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("SurfaceColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("TextColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));
                    b.ToTable("BrandingSettings");
                });

            modelBuilder.Entity("FormBuilder.Backend.Company", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("FCANumber").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("FcaStatus").HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int?>("ParentCompanyId").HasColumnType("int");
                    b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                    b.Property<int>("Type").HasColumnType("int");
                    b.Property<string>("Website").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("FCANumber").IsUnique();
                    b.HasIndex("ParentCompanyId");
                    b.ToTable("Companies");
                });

            modelBuilder.Entity("FormBuilder.Backend.FieldCondition", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("FieldName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int?>("FormFieldId").HasColumnType("int");
                    b.Property<string>("Operator").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int?>("ValidationRuleId").HasColumnType("int");
                    b.Property<string>("Value").HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("FormFieldId"); b.HasIndex("ValidationRuleId");
                    b.ToTable("FieldConditions");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormField", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("FormStepId").HasColumnType("int");
                    b.Property<string>("Label").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Options").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("ReadOnly").HasColumnType("bit");
                    b.Property<bool>("Required").HasColumnType("bit");
                    b.Property<string>("SubFields").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Type").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("FormStepId"); b.ToTable("FormFields");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormSchema", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Version").HasColumnType("int");
                    b.Property<int?>("WorkflowId").HasColumnType("int");
                    b.HasKey("Id"); b.HasIndex("WorkflowId"); b.ToTable("FormSchemas");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormStep", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Conditions").HasColumnType("nvarchar(max)");
                    b.Property<string>("FormSchemaId").HasColumnType("nvarchar(450)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("FormSchemaId"); b.ToTable("FormSteps");
                });

            modelBuilder.Entity("FormBuilder.Backend.HelpArticle", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Category").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Content").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("ShowInAdminPortal").HasColumnType("bit");
                    b.Property<bool>("ShowInBrokerPortal").HasColumnType("bit");
                    b.Property<bool>("ShowInCustomerPortal").HasColumnType("bit");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));
                    b.ToTable("HelpArticles");
                });

            modelBuilder.Entity("FormBuilder.Backend.IntegrationSetting", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Integration").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Key").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<string>("Value").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("Integration", "Key").IsUnique();
                    b.ToTable("IntegrationSettings");
                });

            modelBuilder.Entity("FormBuilder.Backend.TradingName", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("CompanyId").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("EffectiveFrom").HasColumnType("nvarchar(max)");
                    b.Property<string>("EffectiveTo").HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("CompanyId"); b.ToTable("TradingNames");
                });

            modelBuilder.Entity("FormBuilder.Backend.UserAccount", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("CompanyId").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Department").HasColumnType("nvarchar(max)");
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("FirstName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsLockedOut").HasColumnType("bit");
                    b.Property<string>("JobTitle").HasColumnType("nvarchar(max)");
                    b.Property<string>("LastName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("LicenseNumber").HasColumnType("nvarchar(max)");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Phone").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Username").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("CompanyId"); b.HasIndex("Email").IsUnique();
                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("FormBuilder.Backend.ValidationRule", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("FormFieldId").HasColumnType("int");
                    b.Property<string>("Message").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("RuleType").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Value").HasColumnType("nvarchar(max)");
                    b.HasKey("Id"); b.HasIndex("FormFieldId"); b.ToTable("ValidationRules");
                });

            modelBuilder.Entity("FormBuilder.Backend.Workflow", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.HasKey("Id"); b.ToTable("Workflows");
                });

            modelBuilder.Entity("FormBuilder.Backend.WorkflowStage", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsFinal").HasColumnType("bit");
                    b.Property<bool>("IsInitial").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<int>("Order").HasColumnType("int");
                    b.Property<int>("WorkflowId").HasColumnType("int");
                    b.HasKey("Id"); b.HasIndex("WorkflowId"); b.ToTable("WorkflowStages");
                });

            modelBuilder.Entity("FormBuilder.Backend.WorkflowTask", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<int>("Order").HasColumnType("int");
                    b.Property<bool>("Required").HasColumnType("bit");
                    b.Property<int>("StageId").HasColumnType("int");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.HasKey("Id"); b.HasIndex("StageId"); b.ToTable("WorkflowTasks");
                });

            modelBuilder.Entity("FormBuilder.Backend.WorkflowTransition", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Condition").HasColumnType("nvarchar(max)");
                    b.Property<int>("FromStageId").HasColumnType("int");
                    b.Property<string>("Label").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<int>("ToStageId").HasColumnType("int");
                    b.Property<int>("WorkflowId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("FromStageId"); b.HasIndex("ToStageId"); b.HasIndex("WorkflowId");
                    b.ToTable("WorkflowTransitions");
                });

            // ── Relationships ──────────────────────────────────────────────────

            modelBuilder.Entity("FormBuilder.Backend.BusinessRule", b =>
                {
                    b.HasOne("FormBuilder.Backend.FormSchema", "FormSchema").WithMany().HasForeignKey("FormSchemaId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("FormSchema");
                });

            modelBuilder.Entity("FormBuilder.Backend.RuleCondition", b =>
                {
                    b.HasOne("FormBuilder.Backend.BusinessRule", null).WithMany("Conditions").HasForeignKey("BusinessRuleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("FormBuilder.Backend.Address", b =>
                {
                    b.HasOne("FormBuilder.Backend.Company", "Company").WithMany("Addresses").HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Company");
                });

            modelBuilder.Entity("FormBuilder.Backend.Application", b =>
                {
                    b.HasOne("FormBuilder.Backend.UserAccount", "Broker").WithMany().HasForeignKey("BrokerId").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("FormBuilder.Backend.UserAccount", "Client").WithMany().HasForeignKey("ClientId").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("FormBuilder.Backend.Company", "Company").WithMany().HasForeignKey("CompanyId").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("FormBuilder.Backend.WorkflowStage", "CurrentStage").WithMany().HasForeignKey("CurrentStageId").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("FormBuilder.Backend.FormSchema", "FormSchema").WithMany().HasForeignKey("FormSchemaId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("FormBuilder.Backend.Company", "Network").WithMany().HasForeignKey("NetworkId").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("FormBuilder.Backend.Workflow", "Workflow").WithMany().HasForeignKey("WorkflowId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Broker"); b.Navigation("Client"); b.Navigation("Company");
                    b.Navigation("CurrentStage"); b.Navigation("FormSchema"); b.Navigation("Network"); b.Navigation("Workflow");
                });

            modelBuilder.Entity("FormBuilder.Backend.BankDetails", b =>
                {
                    b.HasOne("FormBuilder.Backend.Company", "Company").WithMany("BankAccounts").HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Company");
                });

            modelBuilder.Entity("FormBuilder.Backend.Company", b =>
                {
                    b.HasOne("FormBuilder.Backend.Company", "ParentCompany").WithMany("ChildCompanies").HasForeignKey("ParentCompanyId").OnDelete(DeleteBehavior.NoAction);
                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("FormBuilder.Backend.FieldCondition", b =>
                {
                    b.HasOne("FormBuilder.Backend.FormField", null).WithMany("Conditions").HasForeignKey("FormFieldId").OnDelete(DeleteBehavior.Cascade);
                    b.HasOne("FormBuilder.Backend.ValidationRule", null).WithMany("Conditions").HasForeignKey("ValidationRuleId");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormField", b =>
                {
                    b.HasOne("FormBuilder.Backend.FormStep", null).WithMany("Fields").HasForeignKey("FormStepId").OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FormBuilder.Backend.FormSchema", b =>
                {
                    b.HasOne("FormBuilder.Backend.Workflow", "Workflow").WithMany().HasForeignKey("WorkflowId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormStep", b =>
                {
                    b.HasOne("FormBuilder.Backend.FormSchema", null).WithMany("Steps").HasForeignKey("FormSchemaId").OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FormBuilder.Backend.TradingName", b =>
                {
                    b.HasOne("FormBuilder.Backend.Company", "Company").WithMany("TradingNames").HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Company");
                });

            modelBuilder.Entity("FormBuilder.Backend.UserAccount", b =>
                {
                    b.HasOne("FormBuilder.Backend.Company", "Company").WithMany("Brokers").HasForeignKey("CompanyId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Company");
                });

            modelBuilder.Entity("FormBuilder.Backend.ValidationRule", b =>
                {
                    b.HasOne("FormBuilder.Backend.FormField", null).WithMany("Validators").HasForeignKey("FormFieldId").OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FormBuilder.Backend.WorkflowStage", b =>
                {
                    b.HasOne("FormBuilder.Backend.Workflow", "Workflow").WithMany("Stages").HasForeignKey("WorkflowId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FormBuilder.Backend.WorkflowTask", b =>
                {
                    b.HasOne("FormBuilder.Backend.WorkflowStage", "Stage").WithMany("Tasks").HasForeignKey("StageId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FormBuilder.Backend.WorkflowTransition", b =>
                {
                    b.HasOne("FormBuilder.Backend.WorkflowStage", "FromStage").WithMany("TransitionsOut").HasForeignKey("FromStageId").OnDelete(DeleteBehavior.NoAction).IsRequired();
                    b.HasOne("FormBuilder.Backend.WorkflowStage", "ToStage").WithMany().HasForeignKey("ToStageId").OnDelete(DeleteBehavior.NoAction).IsRequired();
                    b.HasOne("FormBuilder.Backend.Workflow", null).WithMany().HasForeignKey("WorkflowId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("FromStage"); b.Navigation("ToStage");
                });

            modelBuilder.Entity("FormBuilder.Backend.BusinessRule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("FormBuilder.Backend.Company", b =>
                {
                    b.Navigation("Addresses"); b.Navigation("BankAccounts");
                    b.Navigation("Brokers"); b.Navigation("ChildCompanies");
                    b.Navigation("TradingNames");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormField", b =>
                {
                    b.Navigation("Conditions");
                    b.Navigation("Validators");
                });

            modelBuilder.Entity("FormBuilder.Backend.FormSchema", b => { b.Navigation("Steps"); });
            modelBuilder.Entity("FormBuilder.Backend.FormStep", b => { b.Navigation("Fields"); });
            modelBuilder.Entity("FormBuilder.Backend.ValidationRule", b => { b.Navigation("Conditions"); });
            modelBuilder.Entity("FormBuilder.Backend.Workflow", b => { b.Navigation("Stages"); });
            modelBuilder.Entity("FormBuilder.Backend.WorkflowStage", b =>
                {
                    b.Navigation("Tasks");
                    b.Navigation("TransitionsOut");
                });
#pragma warning restore 612, 618
        }
    }
}
