// <auto-generated />
using FormBuilder.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(FormBuilderDbContext))]
    [Migration("20260507120000_AddTemplates")]
    partial class AddTemplates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
