// <auto-generated />
using FormBuilder.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(FormBuilderDbContext))]
    [Migration("20260506140000_AddRuleConditionGroup")]
    partial class AddRuleConditionGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal descriptor — snapshot handles the full model state.
            // This designer file exists solely to supply the [Migration] attribute
            // so EF Core can discover and apply the migration on startup.
        }
    }
}
