// <auto-generated />
using FormBuilder.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(FormBuilderDbContext))]
    [Migration("20260506150000_AddRuleVisibilityFlags")]
    partial class AddRuleVisibilityFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
